version: "3"

services:
  db-postgres-CRUD-node:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-CRUD-node"
    volumes:
      - ./banco-de-dados-CRUD-node:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  banco-de-dados-CRUD-node:
